### ISSUE TITLE
Will the paketobuildpacks/build:full be deprecated later?

### ISSUE THREAD

**Issue by zhoufenqin** [paketo-buildpacks/bionic-full-stack#73]
Hi, I notice that `paketobuildpacks/build:full-cnb` has been removed to `paketobuildpacks/build-bionic-full:latest`, I want to know if the  `paketobuildpacks/build:xxx` will be deprecated later?
Because we will pull the image from the docker hub to our own service registry regularly， and currently the stack repo changed to 
`paketobuildpacks/build-bionic-full`
`paketobuildpacks/build-bionic-base`
`paketobuildpacks/build-bionic-tiny`
`paketobuildpacks/build-jammy-full`
`paketobuildpacks/build-jammy-base`
`paketobuildpacks/build-jammy-tiny`

how do we follow the rename of the repo?  

## Steps to Reproduce

1.

**Comment by robdimsdale** [comment]
We will keep both tags (`paketobuildpacks/build:full-cnb` and `paketobuildpacks/build-bionic-full:latest`) for 18.04 (Bionic) it is deprecated in April 2023.

We will only publish the 22.04 (Jammy) stacks to the `paketobuildpacks/build-jammy-full:latest` style tag. We also publish those with versions under the `paketobuildpacks/build-jammy-full:v1.2.3` style tag, too)

**Comment by robdimsdale** [comment]
I closed this, but please feel free to re-open if you have further questions
